[_]
schema-version = "0.2"

[io.buildpacks]
builder = "paketobuildpacks/builder-jammy-full"

[[io.buildpacks.build.env]]
name = "BP_PHP_SERVER"
value = "nginx"

[[io.buildpacks.build.env]]
name = "BP_PHP_WEB_DIR"
value = "htdocs"

[[io.buildpacks.build.env]]
name = "COMPOSER"
value = "htdocs/composer.json"

[[io.buildpacks.build.env]]
name = "BP_PHP_ENABLE_HTTPS_REDIRECT"
value = "false"
